version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6401:6379"

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      EXPOSED_CLIENT_IPS: "0.0.0.0"
      REDIS_URL: redis://redis:6379
