name: End-to-end Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: codecrafters-io/bittorrent-test-seeder
          ref: main
          path: seeder

      - name: Install torrent client
        run: sudo apt-get install -y aria2

      - name: Download torrent files
        run: ls seeder/torrent_files/*.torrent | xargs -P8 -n1 aria2c --seed-time=0
        timeout-minutes: 2

      # - name: Upload downloaded file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: downloaded-file
      #     path: congratulations.gif

      - name: Verify SHA sum [1]
        run: echo "a672112a70f71e8be8310b2cf182aaf1b8cf152c25e4be4154d021f8e0659d20 congratulations.gif" | sha256sum --check

      - name: Verify SHA sum [2]
        run: echo "4bcfae1708d590ed459d56223e39343536b5fe863bd3c12edc810e3e46633ae5 codercat.gif" | sha256sum --check

      - name: Verify SHA sum [3]
        run: echo "ac41f7ec15b3ce01d63d577508c006d13c662e83c265a1f1d2c393963e287aa1 itsworking.gif" | sha256sum --check

      - name: Verify SHA sum [4]
        run: echo "034779f836050853f4d520fef986db353633d64025241c993bebc0aaf56c081c sample.txt" | sha256sum --check

      - name: Verify SHA sum [5]
        run: echo "edcfa2733b92e9b3de1c0ad744a232b8eb590adbaafb56d455470da6e5317e38 magnet1.gif" | sha256sum --check

      - name: Verify SHA sum [6]
        run: echo "1b8f0a3a903aa6b0c7a3cb1085911911e869e5ced170343a6f7bc0dec888af7b magnet2.gif" | sha256sum --check

      - name: Verify SHA sum [7]
        run: echo "8f9affde72bd2058c86baee5b9615a53cd8280aa00715588749c55b19fa95ef2 magnet3.gif" | sha256sum --check

      - name: Heartbeat
        run: curl https://uptime.betterstack.com/api/v1/heartbeat/2M55J8QACm9v9KP9BQzwppwi

      - name: Send GitHub Action trigger data to Slack workflow
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
