name: End-to-end Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - {
              name: "congratulations.gif",
              sha: "a672112a70f71e8be8310b2cf182aaf1b8cf152c25e4be4154d021f8e0659d20",
            }
          - {
              name: "codercat.gif",
              sha: "4bcfae1708d590ed459d56223e39343536b5fe863bd3c12edc810e3e46633ae5",
            }
          - {
              name: "itsworking.gif",
              sha: "ac41f7ec15b3ce01d63d577508c006d13c662e83c265a1f1d2c393963e287aa1",
            }
          - {
              name: "sample.txt",
              sha: "034779f836050853f4d520fef986db353633d64025241c993bebc0aaf56c081c",
            }
          - {
              name: "magnet1.gif",
              sha: "edcfa2733b92e9b3de1c0ad744a232b8eb590adbaafb56d455470da6e5317e38",
            }
          - {
              name: "magnet2.gif",
              sha: "1b8f0a3a903aa6b0c7a3cb1085911911e869e5ced170343a6f7bc0dec888af7b",
            }
          - {
              name: "magnet3.gif",
              sha: "8f9affde72bd2058c86baee5b9615a53cd8280aa00715588749c55b19fa95ef2",
            }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout seeder code
        uses: actions/checkout@v3
        with:
          repository: codecrafters-io/bittorrent-test-seeder
          ref: main
          path: seeder

      - name: Install torrent client
        run: sudo apt-get install -y aria2

      - name: Download torrent files 10 times in parallel
        run: |
          for i in {1..10}; do
            aria2c --seed-time=0 seeder/torrent_files/**/${{ matrix.file.name }}.torrent -d download_$i &
          done
          wait
        timeout-minutes: 2

      - name: Verify SHA sum for all downloads
        run: |
          for i in {1..10}; do
            echo "${{ matrix.file.sha }} download_$i/${{ matrix.file.name }}" | sha256sum --check
          done

      - name: Send GitHub Action trigger data to Slack workflow
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  heartbeat:
    needs: download
    runs-on: ubuntu-latest
    steps:
      - name: Heartbeat
        run: curl https://uptime.betterstack.com/api/v1/heartbeat/2M55J8QACm9v9KP9BQzwppwi
