name: End-to-end Test
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install torrent client
        run: sudo apt-get install -y aria2

      - name: Download the torrent file
        run: aria2c --seed-time=0 tests/congratulations.gif.torrent

      # - name: Upload downloaded file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: downloaded-file
      #     path: congratulations.gif

      - name: Verify SHA sum
        run: echo "a672112a70f71e8be8310b2cf182aaf1b8cf152c25e4be4154d021f8e0659d20 congratulations.gif" | sha256sum --check

      - name: Heartbeat
        if: always()
        run: curl https://uptime.betterstack.com/api/v1/heartbeat/2M55J8QACm9v9KP9BQzwppwi

      - name: Send GitHub Action trigger data to Slack workflow
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
