name: End-to-end Test
on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install torrent client
        run: sudo apt-get install -y aria2

      - name: Download the torrent file
        run: aria2c --seed-time=0 tests/congratulations.gif.torrent

      # - name: Upload downloaded file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: downloaded-file
      #     path: congratulations.gif

      - name: Verify SHA sum
        run: echo "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad congratulations.gif" | sha256sum --check
